/**
 * example03
 * @author Clay
 * @version V 1.0.0
 */

#ifndef FROMUNDEFINEDTOANY_EXAMPLE03_H
#define FROMUNDEFINEDTOANY_EXAMPLE03_H

#define INCHES_PER_CENTIMETER 0.394
#define CENTIMETERS_PER_INCH 1 / INCHES_PER_CENTIMETER

#define QUARTS_PER_LITER 1.057
#define LITERS_PER_QUART 1 / QUARTS_PER_LITER

#define OUNCES_PER_GRAM 0.035
#define GRAMS_PER_OUNCE 1 / OUNCES_PER_GRAM

#endif //FROMUNDEFINEDTOANY_EXAMPLE03_H